spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scuba?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 19960405
    username: ebbll

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true

logging.level:
  org.hibernate.SQL: debug


jwt:
    secretKey: ${JWT_SECRET_KEY}